clusterDomain: cluster.Domain.local

global:
  storageClass: "rook-cephfs-cluster-retain"
  redis:
    password: Ej*m*Wfw%Fp823ukG

master:
  podAnnotations:
    linkerd.io/inject: enabled
    config.linkerd.io/opaque-ports: "6379"


replica:
  podAnnotations:
    linkerd.io/inject: enabled
    config.linkerd.io/opaque-ports: "6379"

persistentVolume:
  size: 8Gi

image:
  tag: 6.2.6-debian-10-r154

metrics:
  enabled: true