
grafana.ini:
  server:
    domain: grafana-k8s-cluster.Domain.ir
    root_url: "%(protocol)s://%(domain)s/grafana"
    serve_from_sub_path: true

ingress:
  enabled: true
  ingressClassName: nginx
  hosts: 
    - "grafana-k8s-cluster.Domain.ir"
  path: "/grafana"
  tls:
  - secretName: 
    hosts:
    - grafana-k8s-cluster.Domain.ir
    - "*.Domain.ir"

podAnnotations:
  linkerd.io/inject: enabled

persistence:
  enabled: true
  storageClassName: "rook-cephfs-cluster-retain"
  accessModes:
    - ReadWriteOnce
  size: 10Gi
